version: '3.7'
services:
  appenel:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'enelapp'
    ports:
      - "8003:80"
    volumes:
      - ./src:/var/www/html
  dbenel:
    image: mysql:5.7
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbenel:/var/lib/mysql
